backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv2d, [3, 6, 5, 1]]  
  - [-1, 1, BatchNorm2d, [6]]  # add batch norm after Conv2d
  - [-1, 1, ReLU, []]
  - [-1, 1, AvgPool2d, [2, 2]]  
  - [-1, 1, Conv2d, [6, 16, 5, 1]]  
  - [-1, 1, BatchNorm2d, [16]]  # add batch norm after Conv2d
  - [-1, 1, ReLU, []]
  - [-1, 1, AvgPool2d, [2, 2]]  
  - [-1, 1, Flatten, []]  
  - [-1, 1, Linear, [44944, 120]]
  - [-1, 1, BatchNorm1d, [120]]  # add batch norm after Linear
  - [-1, 1, ReLU, []]  
  - [-1, 1, Linear, [120, 84]]
  - [-1, 1, BatchNorm1d, [84]]  # add batch norm after Linear
  - [-1, 1, ReLU, []]  
  - [-1, 1, Linear, [84, 2]] # change output dim to 2
